/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-11-20 13:12:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/common/taglibs.jsp", Long.valueOf(1542684255596L));
    _jspx_dependants.put("jar:file:/D:/work/apache-tomcat-9.0.10/wtpwebapps/supervision-system/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1308098170000L));
    _jspx_dependants.put("jar:file:/D:/work/apache-tomcat-9.0.10/wtpwebapps/supervision-system/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1308098170000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1535646416976L));
    _jspx_dependants.put("jar:file:/D:/work/apache-tomcat-9.0.10/wtpwebapps/supervision-system/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308098170000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write(' ');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no\">\n");
      out.write("    <title>关键词搜索</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/css/bootstrap.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/css/home.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/amazeui.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/font-awesome.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/core.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/menu.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/admin.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/page/typography.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/page/form.css\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- Begin page -->\n");
      out.write("\t<header class=\"am-topbar am-topbar-fixed-top\">\n");
      out.write("\t    <div class=\"am-topbar-left am-hide-sm-only\">\n");
      out.write("\t        <a href=\"/home\" class=\"logo\"><span style=\"color: #d8d8d8\">舆情监督系统</span><i class=\"zmdi zmdi-layers\"></i></a>\n");
      out.write("\t    </div>\n");
      out.write("\t\n");
      out.write("\t    <div class=\"contain\">\n");
      out.write("\t        <ul class=\"am-nav am-navbar-nav am-navbar-left\">\n");
      out.write("\t\n");
      out.write("\t            <li><h4 class=\"page-title\">舆情检索</h4></li>\n");
      out.write("\t        </ul>\n");
      out.write("\t\n");
      out.write("\t        <ul class=\"am-nav am-navbar-nav am-navbar-right\">\n");
      out.write("\t            <li class=\"inform\"><i class=\"am-icon-bell-o\" aria-hidden=\"true\"></i></li>\n");
      out.write("\t            <li class=\"hidden-xs am-hide-sm-only\">\n");
      out.write("\t                <form role=\"search\" class=\"app-search\">\n");
      out.write("\t                    <input type=\"text\" placeholder=\"Search...\" class=\"form-control\">\n");
      out.write("\t                    <a href=\"\"><img src=\"/images/search.png\"></a>\n");
      out.write("\t                </form>\n");
      out.write("\t            </li>\n");
      out.write("\t        </ul>\n");
      out.write("\t    </div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- end page -->\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<div class=\"admin\">\n");
      out.write("\t    <div class=\"admin-sidebar am-offcanvas  am-padding-10\" id=\"admin-offcanvas\">\n");
      out.write("\t        <div class=\"am-offcanvas-bar admin-offcanvas-bar\">\n");
      out.write("\t            <!-- User -->\n");
      out.write("\t            <div class=\"user-box am-hide-sm-only\">\n");
      out.write("\t                <div class=\"user-img\">\n");
      out.write("\t                    <img src=\"/images/avatar-1.jpg\" id=\"user_img\" alt=\"user-img\" title=\"1111\" class=\"img-circle img-thumbnail img-responsive\">\n");
      out.write("\t                    <div class=\"user-status offline\"><i class=\"am-icon-dot-circle-o\" aria-hidden=\"true\"></i></div>\n");
      out.write("\t                </div>\n");
      out.write("\t                <h5><a href=\"#\" id=\"user_name_a\">zhy</a> </h5>\n");
      out.write("\t                <ul class=\"list-inline\">\n");
      out.write("\t                    <li>\n");
      out.write("\t                        <a href=\"#\">\n");
      out.write("\t                            <i class=\"fa fa-cog\" aria-hidden=\"true\"></i>\n");
      out.write("\t                        </a>\n");
      out.write("\t                    </li>\n");
      out.write("\t\n");
      out.write("\t                    <li>\n");
      out.write("\t                        <a href=\"#\" class=\"text-custom\">\n");
      out.write("\t                            <i class=\"fa fa-cog\" aria-hidden=\"true\"></i>\n");
      out.write("\t                        </a>\n");
      out.write("\t                    </li>\n");
      out.write("\t                </ul>\n");
      out.write("\t            </div>\n");
      out.write("\t            <!-- End User -->\n");
      out.write("\t\n");
      out.write("\t            <!-- ========== 左侧菜单栏 ========== -->\n");
      out.write("\t            <!-- sidebar start -->\n");
      out.write("\t            <ul class=\"am-list admin-sidebar-list\">\n");
      out.write("\t                <li><a href=\"/home\"><span class=\"am-icon-home\"></span> 舆情检索</a></li>\n");
      out.write("\t                <li class=\"admin-parent\">\n");
      out.write("\t                    <a class=\"am-cf\" data-am-collapse=\"{target: '#collapse-nav1'}\"><span class=\"am-icon-table\"></span> 话题列表 <span class=\"am-icon-angle-right am-fr am-margin-right\"></span></a>\n");
      out.write("\t                    <ul class=\"am-list am-collapse admin-sidebar-sub am-in\" id=\"collapse-nav1\">\n");
      out.write("\t                        <li><a href=\"/table_basic\" class=\"am-cf\"> 热门话题</a></li>\n");
      out.write("\t                        <li><a href=\"/table_complete\">新闻列表</a></li>\n");
      out.write("\t                    </ul>\n");
      out.write("\t                </li>\n");
      out.write("\t                <li class=\"admin-parent\">\n");
      out.write("\t                    <a class=\"am-cf\" data-am-collapse=\"{target: '#collapse-nav2'}\"><i class=\"am-icon-line-chart\" aria-hidden=\"true\"></i>话题分析 <span class=\"am-icon-angle-right am-fr am-margin-right\"></span></a>\n");
      out.write("\t                    <ul class=\"am-list am-collapse admin-sidebar-sub am-in\" id=\"collapse-nav2\">\n");
      out.write("\t                        <!--  <li><a href=\"/chart_line\" class=\"am-cf\"> 折线图</span></a></li>\n");
      out.write("\t                        <li><a href=\"/chart_columnar\" class=\"am-cf\"> 柱状图</a></li>\n");
      out.write("\t                        <li><a href=\"/chart_pie\" class=\"am-cf\"> 饼状图</a></li>-->\n");
      out.write("\t                    </ul>\n");
      out.write("\t                </li>\n");
      out.write("\t                <li class=\"admin-parent\">\n");
      out.write("\t                    <a class=\"am-cf\" data-am-collapse=\"{target: '#collapse-nav5'}\"><span class=\"am-icon-file\"></span> 话题管理 <span class=\"am-icon-angle-right am-fr am-margin-right\"></span></a>\n");
      out.write("\t                    <ul class=\"am-list am-collapse admin-sidebar-sub am-in\" id=\"collapse-nav5\">\n");
      out.write("\t                        <li><a href=\"/form_basic\" class=\"am-cf\"> 已关注话题</a></li>\n");
      out.write("\t                        <li><a href=\"/form_validate\">话题定制</a></li>\n");
      out.write("\t                    </ul>\n");
      out.write("\t                </li>\n");
      out.write("\t\n");
      out.write("\t            </ul>\n");
      out.write("\t        </div>\n");
      out.write("\t    </div>\n");
      out.write("\t\n");
      out.write("\t    <!-- sidebar end -->\n");
      out.write("\t\n");
      out.write("\t    <!-- ========== Left Sidebar end ========== -->\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t    <!--\t<div class=\"am-g\">-->\n");
      out.write("\t    <!-- ============================================================== -->\n");
      out.write("\t    <!-- Start right Content here -->\n");
      out.write("\t    <div class=\"content-page\" id=\"content\">\n");
      out.write("\t        <!-- Start content -->\n");
      out.write("\t        <div id=\"content\">\n");
      out.write("\t            <div class=\"am-g\" >\n");
      out.write("\t                <!-- Row start -->\n");
      out.write("\t                <div class=\"am-u-sm-12\">\n");
      out.write("\t                    <div id=\"son_div\" >\n");
      out.write("\t                        <div id=\"logo\">\n");
      out.write("\t                            <img id=\"logo_img\" src=\"/images/logo.png\">\n");
      out.write("\t                        </div>\n");
      out.write("\t\n");
      out.write("\t                        <div class=\"col-lg-6\" style=\"margin-top:20px;\">\n");
      out.write("\t                            <div class=\"input-group\">\n");
      out.write("\t                                <input type=\"text\" class=\"form-control\" id=\"keywords\" value=\"美国总统和上海政府官员会面\"> <!--  placeholder=\"请输入要查询的关键字\">-->\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-btn\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/table_complete\"><button class=\"btn btn-default\" id=\"search\" type=\"button\">搜索</button></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t                            </div><!-- /input-group -->\n");
      out.write("\t                        </div><!-- /.col-lg-6 -->\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t                        <br><br>\n");
      out.write("\t\n");
      out.write("\t                        <div id=\"deal_history\">\n");
      out.write("\t                            <button id=\"search_histroy\" class=\"btn btn-default\">搜索历史</button>\n");
      out.write("\t                            <button class=\"btn btn-default\" id=\"empty\">清除历史</button>\n");
      out.write("\t                        </div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t                        <div style=\"margin:20px;\" id=\"history\">\n");
      out.write("\t\n");
      out.write("\t                        </div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t                    </div>\n");
      out.write("\t                </div>\n");
      out.write("\t                <!-- Row end -->\n");
      out.write("\t            </div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t        </div>\n");
      out.write("\t    </div>\n");
      out.write("\t    <!-- end right Content here -->\n");
      out.write("\t    <!--</div>-->\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- navbar -->\n");
      out.write("\t<a href=\"admin-offcanvas\" class=\"am-icon-btn am-icon-th-list am-show-sm-only admin-menu\" data-am-offcanvas=\"{target: '#admin-offcanvas'}\"><!--<i class=\"fa fa-bars\" aria-hidden=\"true\"></i>--></a>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/home.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/amazeui.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/app.js\" ></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/blockUI.js\" ></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("    \n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/common/taglibs.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /WEB-INF/common/taglibs.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/common/taglibs.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/common/taglibs.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("jcPath");
      // /WEB-INF/common/taglibs.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/common/taglibs.jsp(7,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/common/taglibs.jsp(19,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("mainPath");
      // /WEB-INF/common/taglibs.jsp(19,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/common/taglibs.jsp(19,0) '${mainBasePath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${mainBasePath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
